scss_files: 'app/assets/stylesheets/**/*.scss'

linters:
    Comment:
        allowed: '^[/*-]'
    HexNotation:
        style: 'uppercase'
    IdSelector:
        enabled: false
    Indentation:
        width: 4
    NestingDepth:
        max_depth: 3
    PropertySpelling:
        extra_properties: "place-items"
    SingleLinePerSelector:
        enabled: false
