- name: Discord Webhook Notify
  uses: rjstone/discord-webhook-notify@v1.0.4
    with:
    severity: info
    color: '#ff00aa'
    details: 'Custom details: Somebody set up us the bomb.'
    webhookUrl: ${{ secrets.OCTO_BOT }}
