- name: PR Opened
    uses: rjstone/discord-webhook-notify@v1
    with:
        severity: info
        color: '#ff00aa'
        details: 'Custom details: Somebody set up us the bomb.'
        webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
